// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tinxLOF9NvfEO0YeG-Cz3IApoDtsKc4',
    appId: '1:1009736891924:web:f08fa7d090f8cf338ef101',
    messagingSenderId: '1009736891924',
    projectId: 'ulmgap-prod',
    authDomain: 'ulmgap-prod.firebaseapp.com',
    storageBucket: 'ulmgap-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTs0grtLAbxCi7fmTfWlIe5R90OBqH1Do',
    appId: '1:1009736891924:android:c7b327e3214103798ef101',
    messagingSenderId: '1009736891924',
    projectId: 'ulmgap-prod',
    storageBucket: 'ulmgap-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWyuLT5ydwHH_nJ18alFx46O-8pDFm7Vc',
    appId: '1:1009736891924:ios:17f36785c749078b8ef101',
    messagingSenderId: '1009736891924',
    projectId: 'ulmgap-prod',
    storageBucket: 'ulmgap-prod.firebasestorage.app',
    iosBundleId: 'com.ulmgap.ulmgap',
  );
}
