// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_PPegQoqgf4zffj1AELkGxwEWB6P12U4',
    appId: '1:237446007254:web:db899714f2670c76da7c77',
    messagingSenderId: '237446007254',
    projectId: 'ulmgap-dev',
    authDomain: 'ulmgap-dev.firebaseapp.com',
    storageBucket: 'ulmgap-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54Eoloyw-jmWxHa9rUuprTGr2OvPr7w8',
    appId: '1:237446007254:android:40657246512ecc24da7c77',
    messagingSenderId: '237446007254',
    projectId: 'ulmgap-dev',
    storageBucket: 'ulmgap-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHqcGnyRig1Z8efcNcMqd1ZV4uKBBdukc',
    appId: '1:237446007254:ios:0883add2f39dc8fcda7c77',
    messagingSenderId: '237446007254',
    projectId: 'ulmgap-dev',
    storageBucket: 'ulmgap-dev.firebasestorage.app',
    iosBundleId: 'com.ulmgap.ulmgap',
  );
}
